spring:
    cloud:
        gateway:
            routes:
                - id: tour-service
                  uri: http://localhost:8082
                  predicates:
                    - Path=/tours/**
                - id: packages-route
                  uri: http://localhost:8082
                  predicates:
                    - Path=/packages/**